apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-webapp
  template:
    metadata:
      labels:
        app: sample-webapp
    spec:
      containers:
        - name: webapp
          image: shubhambehra/sample-webapp:v1
          ports:
            - containerPort: 8080


# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: webapp-service
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 80
#     targetPort: 8080
#   selector:
#     app: sample-webapp
